// sveltekit-prototype/src/routes/browse/+page.svelte
<script lang="ts">
	import { Search, Sparkles, Wand, Terminal } from 'lucide-svelte';
	import { onMount } from 'svelte';
	import { locale } from '$lib/stores/i18n';
	import { loadPromptsByLocale } from '$lib/promptLoader';
	import type { PromptMetadata } from '$lib/types';

	// カテゴリごとの色マップ
	const CATEGORY_COLORS: Record<string, { from: string; to: string }> = {
		coding: { from: '#2E578C', to: '#182D40' },
		audio: { from: '#BF807A', to: '#2E578C' },
		documentation: { from: '#BF807A', to: '#F2F2F2' },
		image: { from: '#BF807A', to: '#2E578C' },
		meta: { from: '#BF807A', to: '#592A2A' },
		methodology: { from: '#2E578C', to: '#BF807A' },
		'mind-mapping': { from: '#2E578C', to: '#F2F2F2' },
		writing: { from: '#BF807A', to: '#182D40' },
		'aws-certification': { from: '#182D40', to: '#2E578C' },
		'Company-as-a-Code': { from: '#F2F2F2', to: '#182D40' },
		diagram: { from: '#2E578C', to: '#BF807A' },
		education: { from: '#2E578C', to: '#F2F2F2' },
		other: { from: '#2E578C', to: '#BF807A' }
	};

	// ステート
	let prompts: PromptMetadata[] = $state([]);
	let loading = $state(true);
	let t: Record<string, any> = $state({});

	// 翻訳データをロード
	$effect(() => {
		const loadTranslations = async () => {
			try {
				const loc = locale.get();
				const module = await import(`../../i18n/${loc}.json`);
				t = module.default;
			} catch (e) {
				console.error('Failed to load translations:', e);
			}
		};
		loadTranslations();
	});

	// プロンプトを読み込み
	onMount(async () => {
		try {
			const loc = locale.get();
			prompts = await loadPromptsByLocale(loc);
		} catch (e) {
			console.error('Failed to load prompts:', e);
		} finally {
			loading = false;
		}
	});

	// カテゴリラベルを取得
	function getCategoryLabel(category: string): string {
		return t?.categories?.[category] || category;
	}

	// カラーセットを取得
	function getColorSet(category: string) {
		return CATEGORY_COLORS[category] || CATEGORY_COLORS['other'];
	}
</script>

<div class="container mx-auto px-4 py-8 space-y-8 page-enter">
	<div class="flex items-center justify-between">
		<h1 class="text-3xl font-bold font-kaisei gradient-text flex items-center gap-2">
			<Wand class="h-8" />
			{t?.browse?.title || 'プロンプト一覧'}
		</h1>
		<div class="relative">
			<input
				type="text"
				placeholder={t?.browse?.searchPlaceholder || 'プロンプトを検索...'}
				class="pl-10 pr-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent font-zen bg-white text-slate-800 placeholder:text-slate-500"
			/>
			<Search class="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-slate-500" />
		</div>
	</div>

	{#if loading}
		<div class="text-center py-12">
			<div class="magic-loading mx-auto">
				<div class="orbit-ring"></div>
				<div class="magic-trail"></div>
				<div class="magic-wand h-10 w-10">
					<Wand class="text-primary h-full w-full" />
				</div>
				<div class="magic-sparkles">
					<div class="sparkle"></div>
					<div class="sparkle"></div>
					<div class="sparkle"></div>
					<div class="sparkle"></div>
					<div class="sparkle"></div>
				</div>
			</div>
			<p class="text-slate-800 font-zen mt-4 opacity-80">
				{t?.browse?.loading || '魔法の図書館から知識を呼び出し中...'}
			</p>
		</div>
	{:else if prompts.length === 0}
		<div class="text-center py-8 bg-white rounded-xl border border-slate-200 p-12">
			<p class="text-slate-800 font-zen">{t?.browse?.noPrompts || 'まだプロンプトが投稿されていません。'}</p>
		</div>
	{:else}
		<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
			{#each prompts as prompt, index}
				{@const isShellScript = prompt.path.endsWith('.sh')}
				{@const IconComponent = isShellScript ? Terminal : Wand}
				{@const categoryKey = prompt.category || 'other'}
				{@const colorSet = getColorSet(categoryKey)}
				{@const gradientFrom = colorSet.from}
				{@const gradientTo = colorSet.to}

				<div
					class="card rounded-xl p-6 transform transition-all duration-300 hover:-translate-y-2 hover:shadow-xl relative overflow-hidden group h-full flex flex-col min-h-[260px] fade-in-up"
					style="animation-delay: {index * 0.05}s;"
				>
					<div
						class="absolute inset-0 flowing-background"
						style="--gradient-from: {gradientFrom}; --gradient-to: {gradientTo};"
					>
						<div class="w-full h-full flex items-center justify-center">
							<IconComponent class="h-48 w-48 transform rotate-12" />
						</div>
					</div>
					<div class="relative z-10 flex flex-col flex-1">
						<a href="/wiki/{prompt.path.replace(/^\/+/, '')}" class="block h-full">
							<div class="flex items-start space-x-3 mb-2">
								<div
									class="flowing-icon h-8 w-8 min-w-8 max-w-8 rounded-full flex items-center justify-center transform transition-transform duration-300 group-hover:scale-110"
									style="--gradient-from: {gradientFrom}; --gradient-to: {gradientTo};"
								>
									<IconComponent class="h-4 w-4 text-white" />
								</div>
								<div class="flex-1 min-w-0">
									<h3 class="font-kaisei text-lg font-bold text-slate-900 leading-snug">
										<span class="keyword line-clamp-2 break-words block">{prompt.title}</span>
									</h3>
									<p class="prose prose-xs prose-primary prose-headings:text-xs prose-p:text-xs text-slate-800 font-zen line-clamp-2 mt-1 max-w-xs">
										{prompt.description}
									</p>
									<div class="flex flex-wrap gap-2 mt-2">
										<span
											class="inline-flex items-center px-3 py-1 rounded-full shadow bg-gradient-to-r text-white text-xs font-bold transition-opacity hover:opacity-90"
											style="background: linear-gradient(to right, {gradientFrom}, {gradientTo})"
										>
											{getCategoryLabel(categoryKey)}
										</span>
										{#if isShellScript}
											<span
												class="inline-flex items-center px-3 py-1 rounded-full shadow bg-gradient-to-r from-slate-600 to-slate-800 text-white text-xs font-bold transition-opacity hover:opacity-90"
											>
												{t?.browse?.script || 'スクリプト'}
											</span>
										{/if}
										{#if prompt.tag}
											<span
												class="inline-flex items-center px-3 py-1 rounded-full shadow bg-gradient-to-r from-accent to-primary text-white text-xs font-bold transition-opacity hover:opacity-90"
											>
												{prompt.tag}
											</span>
										{/if}
									</div>
								</div>
							</div>
						</a>
						<div class="relative z-10 mt-auto pt-2 border-t border-slate-100">
							<div class="text-xs text-slate-800 font-zen">
								{t?.browse?.updated || '更新日'}:
								{new Date(prompt.lastModified).toLocaleDateString(locale.get() === 'ja' ? 'ja-JP' : 'en-US', {
									year: 'numeric',
									month: 'short',
									day: 'numeric'
								})}
							</div>
						</div>
					</div>
				</div>
			{/each}
		</div>
	{/if}

	<div class="highlight-box mt-8">
		<p class="font-zen text-center text-lg text-slate-900">
			{t?.browse?.highlight || '新しいプロンプトは毎日追加されています。あなたのアイデアも共有してみませんか？'}
		</p>
	</div>
</div>

// MysticLibrary/src/pages/Browse.tsx
import { Search, Eye } from 'lucide-react';
import { useState, useEffect } from 'react';
import { supabase } from '../lib/supabase';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faHatWizard } from '@fortawesome/free-solid-svg-icons';
import type { Prompt } from '../lib/supabase';
import { Link } from 'react-router-dom';
import { LikeButton } from '../components/LikeButton';
import * as Icons from 'lucide-react';

export function Browse() {
  const [prompts, setPrompts] = useState<Prompt[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchPrompts() {
      try {
        const { data, error } = await supabase
          .from('prompts')
          .select(`
            id,
            title,
            description,
            views_count,
            likes_count,
            icon_name,
            gradient_from,
            gradient_to,
            category:categories(name),
            user:profiles!prompts_user_id_fkey(username),
            tags!prompt_tags(
              id,
              name
            )
          `)
          .eq('is_published', true)
          .order('created_at', { ascending: false });

        if (error) throw error;
        setPrompts(data || []);
      } catch (error) {
        console.error('Error fetching prompts:', error);
      } finally {
        setLoading(false);
      }
    }

    fetchPrompts();
  }, []);

  return (
    <div className="space-y-8">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold font-kaisei gradient-text flex items-center gap-2">
          <FontAwesomeIcon icon={faHatWizard} className="h-8" />
          プロンプト一覧
        </h1>
        <div className="relative">
          <input
            type="text"
            placeholder="プロンプトを検索..."
            className="pl-10 pr-4 py-2 border border-primary rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent font-zen"
          />
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-primary" />
        </div>
      </div>

      {loading ? (
        <div className="text-center py-8">
          <div className="animate-spin h-8 w-8 mx-auto">
            <FontAwesomeIcon icon={faHatWizard} className="text-primary" />
          </div>
        </div>
      ) : prompts.length === 0 ? (
        <div className="text-center py-8">
          <p className="text-primary-dark font-zen">まだプロンプトが投稿されていません。</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {prompts.map((prompt) => {
            const IconComponent = Icons[prompt.icon_name as keyof typeof Icons] || Icons.Wand;
            const gradientFrom = prompt.gradient_from || '#2E578C';
            const gradientTo = prompt.gradient_to || '#BF807A';
            
            return (
              <div 
                key={prompt.id} 
                className="card bg-white rounded-xl shadow-md border border-light p-6 transform transition-all duration-300 hover:-translate-y-2 hover:shadow-xl hover:shadow-primary/20 relative overflow-hidden group"
              >
                <div 
                  className="absolute inset-0 flowing-background"
                  style={{
                    '--gradient-from': gradientFrom,
                    '--gradient-to': gradientTo,
                  } as React.CSSProperties}
                >
                  <div className="w-full h-full flex items-center justify-center">
                    <IconComponent className="h-48 w-48 transform rotate-12" />
                  </div>
                </div>
                <div className="space-y-4 relative z-10">
                  <Link
                    to={`/prompts/${prompt.id}`}
                    className="block"
                  >
                    <div className="flex items-center space-x-2">
                      <div
                        className="flowing-icon h-8 w-8 rounded-full flex items-center justify-center transform transition-transform duration-300 group-hover:scale-110"
                        style={{
                          '--gradient-from': gradientFrom,
                          '--gradient-to': gradientTo,
                        } as React.CSSProperties}
                      >
                        <IconComponent className="h-4 w-4 text-white" />
                      </div>
                      <div>
                        <h3 className="font-kaisei text-lg font-bold text-primary-dark">
                          <span className="keyword">{prompt.title}</span>
                        </h3>
                        <p className="text-sm text-primary-dark font-zen">
                          作成者：{prompt.user?.username}
                        </p>
                      </div>
                    </div>
                    <p className="text-primary-dark line-clamp-3 font-zen mt-2">{prompt.description}</p>
                  </Link>
                  <div className="space-y-3">
                    <div className="flex flex-wrap gap-2">
                      {prompt.category && (
                        <span className="px-3 py-1 rounded-full text-sm font-zen bg-primary bg-opacity-10 text-primary transition-colors duration-300 hover:bg-opacity-20">
                          {prompt.category.name}
                        </span>
                      )}
                      {prompt.tags && prompt.tags.map((tag) => (
                        <span
                          key={tag.id}
                          className="px-3 py-1 rounded-full text-sm font-zen bg-accent bg-opacity-10 text-accent transition-colors duration-300 hover:bg-opacity-20"
                        >
                          {tag.name}
                        </span>
                      ))}
                    </div>
                    <div className="flex items-center justify-end space-x-4 text-sm text-primary-dark">
                      <span className="flex items-center space-x-1">
                        <Eye className="h-4 w-4" />
                        <span className="font-kaisei">{prompt.views_count}</span>
                      </span>
                      <LikeButton promptId={prompt.id} initialLikes={prompt.likes_count || 0} size="sm" />
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      <div className="highlight-box mt-8">
        <p className="font-zen text-center text-lg">
          <span className="keyword">新しいプロンプト</span>は毎日追加されています。
          あなたの<span className="keyword">アイデア</span>も共有してみませんか？
        </p>
      </div>
    </div>
  );
}
